name: Save Journal Entry

on:
  repository_dispatch:
    types: [save-journal]

jobs:
  save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo using PAT
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN_BUJO }}

      - name: Decode and write journal
        run: |
          mkdir -p journals
          echo "${{ github.event.client_payload.content }}" | base64 -d > journals/journal-${{ github.event.client_payload.date }}.html

      - name: Commit and push journal
        env:
          GH_TOKEN_BUJO: ${{ secrets.GH_TOKEN_BUJO }}
        run: |
          git config user.name "Auto Journal Bot"
          git config user.email "bot@users.noreply.github.com"
          git add journals/
          git commit -m "📓 Save journal for ${{ github.event.client_payload.date }}" || echo "No changes to commit"
          git pull --rebase origin main || echo "⚠️ Rebase failed, possibly due to conflict"
          git push https://x-access-token:${GH_TOKEN_BUJO}@github.com/lebron1212/bulletjournal.git HEAD:main || echo "⚠️ Push failed"
