name: Save Journal Entry

on:
  repository_dispatch:
    types: [save-journal]

jobs:
  save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Decode and write journal
        run: |
          mkdir -p journals
          echo "${{ github.event.client_payload.content }}" | base64 -d > journals/journal-${{ github.event.client_payload.date }}.html

      - name: Commit journal
        run: |
          git config user.name "Auto Journal Bot"
          git config user.email "bot@users.noreply.github.com"
          git add journals/
          git commit -m "\ud83d\udcd3 Save journal for ${{ github.event.client_payload.date }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
